#!/bin/bash

echo ""
echo "This script copies supervisor config for auto launching"
echo "to /etc/supervisor/conf.d"
echo ""

sudo cp `rospack find sphand_driver`/supervisor/launch_left_gripper.conf /etc/supervisor/conf.d
sudo cp `rospack find sphand_driver`/supervisor/check_i2cdetect.conf /etc/supervisor/conf.d
